name:                caloree-cli
version:             0.1.0.0
github:              "githubuser/caloree-cli"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2022 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/caloree-cli#readme>

dependencies:
- base >= 4.7 && < 5
- colonnade
- fmt
- text
- vector
- req
- aeson
- mtl
- transformers
- bytestring
- utf8-string
- profunctors
- optparse-applicative
- time

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -threaded

default-extensions: 
  - DeriveFunctor 
  - DeriveFoldable 
  - DeriveGeneric
  - DeriveTraversable
  - ExplicitForAll
  - RecordWildCards
  - NamedFieldPuns
  - GeneralisedNewtypeDeriving
  - OverloadedStrings
  - OverloadedLists
  - TypeApplications
  - ScopedTypeVariables
  - InstanceSigs
  - MultiParamTypeClasses
  - FunctionalDependencies
  - GeneralizedNewtypeDeriving
  - FlexibleContexts
  - FlexibleInstances
  - DefaultSignatures
  - TypeOperators
  - DataKinds
  - KindSignatures
  - LambdaCase
  - GADTs
  - StandaloneDeriving
  - RankNTypes

library:
  source-dirs: src

executables:
  caloree-cli-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - caloree-cli

tests:
  caloree-cli-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - caloree-cli
